/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be committed with the
// project. It is regenerated by Expo and provides the ambient types used by
// the app (including process.env.EXPO_PUBLIC_* variables).
